# Generated by Django 2.1.4 on 2019-01-18 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dc_management', '0052_auto_20190118_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dua_required', models.BooleanField(null=True)),
                ('prj_desc_required', models.BooleanField(null=True)),
                ('sys_desc_required', models.BooleanField(null=True)),
                ('help_required', models.BooleanField(null=True)),
                ('access_cost', models.IntegerField(null=True)),
                ('public', models.BooleanField(null=True)),
                ('time_required', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('affiliation', models.CharField(choices=[('AC', 'Academic'), ('ME', 'Medical provider / Hospital'), ('GV', 'Government'), ('PR', 'Private institution')], default='GV', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('ds_id', models.CharField(max_length=128, null=True, unique=True, verbose_name='Dataset ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('landing_url', models.URLField(max_length=256, null=True)),
                ('comments', models.TextField(null=True)),
                ('access_requirements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataAccess')),
            ],
        ),
        migrations.CreateModel(
            name='DataUseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('duaid', models.CharField(max_length=128, unique=True, verbose_name='DUA ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('separate_attestation', models.BooleanField(null=True)),
                ('scope', models.CharField(choices=[('US', 'User'), ('PI', 'Principle Investigator'), ('PJ', 'Project'), ('IN', 'Institution')], default='US', max_length=2)),
                ('date_signed', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('destruction_required', models.BooleanField(null=True)),
                ('mixing_allowed', models.BooleanField(null=True)),
                ('storage_requirements', models.TextField(blank=True, null=True)),
                ('access_conditions', models.TextField(blank=True, null=True)),
                ('access_requirements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataAccess')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='dc_management.Person')),
                ('datasets', models.ManyToManyField(to='datacatalog.Dataset')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_person', to='dc_management.Person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataProvider')),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(null=True, to='dc_management.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('keyword', models.CharField(max_length=64)),
                ('definition', models.TextField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(null=True, to='datacatalog.Keyword'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='record_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
