# Generated by Django 2.1.4 on 2019-01-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacatalog', '0002_auto_20190118_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccess',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='record_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='record_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='record_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='dept',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='record_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='record_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='record_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='name',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
    ]
