# Generated by Django 2.1.4 on 2019-01-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0003_auto_20190119_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataProvider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='access_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='dua_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='help_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='prj_desc_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='sys_desc_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='time_required',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='dept',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='access_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataAccess'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ds_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Dataset ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='datacatalog.Keyword'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='landing_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
