# Generated by Django 2.1.4 on 2019-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0005_auto_20190129_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccess',
            name='curated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='curated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='curated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='curated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
