# Generated by Django 2.1.4 on 2019-06-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0006_auto_20190206_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
