# Generated by Django 2.1.4 on 2019-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0007_auto_20190618_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauseagreement',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
