# Generated by Django 2.1.4 on 2019-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0009_auto_20190718_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccess',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='curated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
