# Generated by Django 2.1.4 on 2019-07-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0010_auto_20190719_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('template', models.CharField(max_length=256, unique=True)),
                ('reference', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('obsolete', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, help_text='https://schema.org/description', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ds_id',
            field=models.CharField(blank=True, help_text='http://schema.org/identifier', max_length=128, null=True, unique=True, verbose_name='Dataset ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='https://schema.org/codeValue', to='datacatalog.Keyword'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='period_end',
            field=models.DateField(blank=True, help_text='https://schema.org/Date', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='period_start',
            field=models.DateField(blank=True, help_text='https://schema.org/Date', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(help_text='https://schema.org/publisher', on_delete=django.db.models.deletion.CASCADE, to='datacatalog.DataProvider'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(help_text='The name of the dataset, usually one sentence or short description of the dataset.', max_length=256, unique=True),
        ),
    ]
