# Generated by Django 2.1.4 on 2019-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0011_auto_20190724_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='data_fields',
            field=models.TextField(blank=True, help_text='https://schema.org/description', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='media_subtype',
            field=models.ManyToManyField(blank=True, to='datacatalog.MediaSubType'),
        ),
    ]
