# Generated by Django 2.1.4 on 2019-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0013_auto_20190724_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasubtype',
            name='template',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
