# Generated by Django 2.1.4 on 2019-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0014_auto_20190724_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasubtype',
            name='reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
