# Generated by Django 2.1.4 on 2019-07-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0015_auto_20190724_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='description',
            field=models.CharField(help_text='Description of the field', max_length=256),
        ),
    ]
