# Generated by Django 2.1.4 on 2019-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0016_auto_20190724_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='scope',
            field=models.CharField(help_text='Descriptions of the scope of the data (eg. min, max, number of records, number of null values, number of unique values)', max_length=256, null=True),
        ),
    ]
