# Generated by Django 2.1.4 on 2019-10-22 21:45

import datacatalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacatalog', '0018_auto_20190725_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='defers_to_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrules', to='datacatalog.DataUseAgreement'),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to=datacatalog.models.project_directory_path),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='privileged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='supersedes_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='datacatalog.DataUseAgreement'),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='governance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.GovernanceType'),
        ),
    ]
