# Generated by Django 2.1.4 on 2020-03-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('datacatalog', '0019_auto_20191022_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccess',
            name='restricted',
            field=models.ManyToManyField(related_name='restricted_access', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='restricted',
            field=models.ManyToManyField(related_name='restricted_dataset', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='datauseagreement',
            name='restricted',
            field=models.ManyToManyField(related_name='restricted_dua', to='persons.Person'),
        ),
    ]
