# Generated by Django 2.1.4 on 2020-08-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacatalog', '0020_auto_20200310_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('impact_level', models.CharField(help_text='Level as defined by the standard', max_length=32, verbose_name='Impact Level')),
                ('impact_rank', models.IntegerField(help_text='Rank of impact: 1 is highest risk')),
                ('standard', models.CharField(help_text='Standard defining the impact level', max_length=32, verbose_name='Impact Level')),
                ('definition', models.TextField()),
                ('link', models.URLField()),
                ('record_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='record_scale',
            field=models.CharField(blank=True, choices=[('UN', '< 10'), ('TE', '10s'), ('HU', '100s'), ('TH', '1,000s'), ('TT', '10,000s'), ('HT', '100,000s'), ('MI', '1,000,000s')], help_text='indicate the scale, based on the number of records', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='datacatalog.Dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='cil',
            field=models.ManyToManyField(blank=True, help_text='Select an impact level based on ', to='datacatalog.ConfidentialityImpact'),
        ),
    ]
