# Generated by Django 2.1.4 on 2020-08-20 19:02

import datacatalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0021_auto_20200804_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='data_dictionary',
            field=models.FileField(blank=True, help_text='CSV or TSV file of each data field and its description.', null=True, upload_to=datacatalog.models.dictionary_directory_path),
        ),
        migrations.AddField(
            model_name='dataset',
            name='num_records',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of records'),
        ),
        migrations.AlterField(
            model_name='confidentialityimpact',
            name='standard',
            field=models.CharField(help_text='Standard defining the impact level', max_length=32, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='cil',
            field=models.ManyToManyField(blank=True, help_text='Select an impact level based on data risk', to='datacatalog.ConfidentialityImpact'),
        ),
    ]
