# Generated by Django 2.1.4 on 2021-02-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0022_auto_20200820_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='linked_data',
            field=models.ManyToManyField(related_name='_dataset_linked_data_+', to='datacatalog.Dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='restricted_dataset', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
