# Generated by Django 3.2 on 2021-10-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0027_auto_20211020_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccess',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.dataset'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.project'),
        ),
    ]
