# Generated by Django 3.2 on 2021-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0029_auto_20211021_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionrequest',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
