# Generated by Django 3.2 on 2021-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0032_auto_20211103_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionrequest',
            name='ticket',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
