# Generated by Django 3.2 on 2021-11-10 23:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('datacatalog', '0033_alter_retentionrequest_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='public',
            field=models.BooleanField(blank=True, default=True, help_text='Whether to make this record visible in the Data Catalog', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Group responsible for publication of the data set', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_publisher', to='datacatalog.dataprovider'),
        ),
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_person', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.DateField(blank=True, help_text='Expected end date of project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_id',
            field=models.CharField(blank=True, help_text='Weill research gateway grant ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone',
            field=models.CharField(choices=[('', '--- choose one ---'), ('PU', 'Publication'), ('CO', 'Project/Grant completion'), ('TR', 'Leaving Weill Cornell Medicine')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone_date',
            field=models.DateField(default=datetime.date.today, help_text='The date this milestone comes into effect'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone_pointer',
            field=models.CharField(default='Enter reference here', help_text='DOI, WRG ID, or HR reference', max_length=64),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='name',
            field=models.CharField(help_text='A name to help identify this request', max_length=256, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Select from your available projects', null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.project'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='to_archive',
            field=models.ManyToManyField(help_text='Select all data for retention from the project chosen above', related_name='retention_requests', to='datacatalog.DataAccess'),
        ),
    ]
