# Generated by Django 3.2 on 2021-11-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0034_auto_20211110_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccess',
            name='filepaths',
            field=models.TextField(blank=True, help_text='describe the paths to all directories and/or files', null=True),
        ),
        migrations.RemoveField(
            model_name='dataaccess',
            name='metadata',
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='link this entry to selected Data Catalog record(s)', to='datacatalog.Dataset'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='shareable_link',
            field=models.URLField(blank=True, help_text='system-generated shareable URL to the data', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='storage_type',
            field=models.ForeignKey(blank=True, help_text='Select the system storing the data', null=True, on_delete=django.db.models.deletion.PROTECT, to='datacatalog.storagetype'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='unique_id',
            field=models.CharField(blank=True, help_text='system-generated unique identifier', max_length=256, null=True),
        ),
    ]
