# Generated by Django 3.2 on 2022-03-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('datacatalog', '0036_auto_20211126_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_editors',
            field=models.ManyToManyField(blank=True, help_text='Additional people to give access to edit the project', null=True, related_name='other_editors', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='project',
            name='other_pis',
            field=models.ManyToManyField(blank=True, help_text='Additional PIs related to the project', null=True, related_name='other_pis', to='persons.Person'),
        ),
    ]
