# Generated by Django 3.2 on 2022-03-22 02:12

import datacatalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('datacatalog', '0037_auto_20220320_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionrequest',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='retentionrequest',
            name='inventory',
            field=models.FileField(help_text='Document list of all files archived', null=True, upload_to=datacatalog.models.inventory_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_editors',
            field=models.ManyToManyField(blank=True, help_text='Additional people to give access to edit the project', related_name='other_editors', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_pis',
            field=models.ManyToManyField(blank=True, help_text='Additional PIs related to the project', related_name='other_pis', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='methodfile',
            field=models.FileField(help_text='\n                                      Upload a document describing steps required to generate results files from \n                                      source data \n                                      ', null=True, upload_to=datacatalog.models.method_directory_path),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone_pointer',
            field=models.CharField(help_text='DOI, WRG ID, or HR reference', max_length=64),
        ),
    ]
