# Generated by Django 3.2 on 2022-05-25 19:32

import datacatalog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('datacatalog', '0038_auto_20220321_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccess',
            name='multifiles',
            field=models.FileField(blank=True, help_text='upload files directly for archiving', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='filepaths',
            field=models.TextField(blank=True, help_text='describe the full path to all directories and/or files, e.g. libsrv.med.cornell.edu/my_lab/myfolder/data.csv', null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='link this dataset to selected Data Catalog record(s)', to='datacatalog.Dataset'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='public_data',
            field=models.BooleanField(blank=True, default=False, help_text='Choose yes to make this information publicly visible', null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='shareable_link',
            field=models.URLField(blank=True, help_text='system-generated shareable link to the data, e.g. OneDrive, LabArchives', max_length=1024, null=True, verbose_name='Link to your data location'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='steward_email',
            field=models.EmailField(blank=True, help_text='Person to contact for data access', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='unique_id',
            field=models.CharField(blank=True, help_text='system-generated unique identifier for e.g. Starfish', max_length=256, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='num_records',
            field=models.IntegerField(blank=True, help_text='sample size of the dataset', null=True, verbose_name='Number of records'),
        ),
        migrations.AlterField(
            model_name='datauseagreement',
            name='scope',
            field=models.CharField(choices=[('US', 'User'), ('PI', 'Principal Investigator'), ('PJ', 'Project'), ('IN', 'Institution')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.DateField(blank=True, help_text='expected completion date of project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_id',
            field=models.CharField(blank=True, help_text='WRG project ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_editors',
            field=models.ManyToManyField(blank=True, help_text='additional people to give access to edit the project', related_name='other_editors', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_pis',
            field=models.ManyToManyField(blank=True, help_text='additional PIs related to the project', related_name='other_pis', to='persons.Person', verbose_name='Other PIs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pi_project_person', to='persons.person', verbose_name='PI'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='methodfile',
            field=models.FileField(help_text='\n                                      upload a document describing steps required to produce output data from raw data \n                                      ', null=True, upload_to=datacatalog.models.method_directory_path, verbose_name='Methods file'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone_date',
            field=models.DateField(default=datetime.date.today, help_text='expected completion date of milestone'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='milestone_pointer',
            field=models.CharField(help_text='DOI of published article, WRG project ID, or HR offboarding form ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='name',
            field=models.CharField(help_text='enter a name to identify this request', max_length=256, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='retentionrequest',
            name='to_archive',
            field=models.ManyToManyField(help_text='select all data for retention from the project chosen above', related_name='retention_requests', to='datacatalog.DataAccess'),
        ),
    ]
